# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M_Qsp2cKW-pRW5tPDsUgmPueEn4C8oj9
"""

import streamlit as st
from docx import Document
from docx.shared import Inches

def is_odd(n):
    return n % 2 != 0

st.title("Check if Number is Odd and Download Word File")

# Get user input
number = st.text_input("Enter a number:")

# Check if number is odd
if number.isdigit() and is_odd(int(number)):
    # Create a new Word document
    doc = Document()
    doc.add_heading('Odd Number', 0)
    doc.add_paragraph(f'The number {number} is odd!')

    # Download the Word document
    st.download_button(
        label="Download Word Document",
        data=doc,
        file_name="file1.docx",
        mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    )
else:
    st.write("Please enter a valid odd number.")